### ISSUE TITLE
Repo should follow GitFlow workflow

### ISSUE THREAD

**Issue by raghavpuri** [scorelab/SAMS#2]
This repos should follow Gitflow workflow and follow are the items you have to check. 
- [x] There is a `master` branch and a `develop` branch.
- [x] `master` branch is locked for direct commits and, 
  - [x] Require pull request reviews before merging is active
  - [x] Require status checks to pass before merging is active
    - [x] Require branches to be up to date before merging
    - [x] Appropriate Status checks are required
  - [x] Enforce all configured restrictions for administrators is active
  - [x] Restrict only maintainers group can push to the master branch
- [x] `develop` branch is locked for direct commits and,
  - [x] Require pull request reviews before merging
    - [x] Dismiss stale pull request approvals when new commits are pushed is active
  - [x] Require pull request reviews before merging is active
  - [x] Require status checks to pass before merging is active
    - [x] Require branches to be up to date before merging
    - [x] Appropriate Status checks are required
  - [x] Enforce all configured restrictions for administrators is active
  - [x] Restrict only maintainers group can push to the master branch

**Comment by Thuan2000** [comment]
Hi @raghavpuri , thank you for bringing this up. I have completed all the checks. As for the status checks, there is no need as this is a prosthetic repo meant for Google Code-in use only. Many thanks!
